/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/challenges` | `/challenges`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExerciseCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExerciseStep`; params?: Router.UnknownInputParams; } | { pathname: `/components/MultipleChoiceOption`; params?: Router.UnknownInputParams; } | { pathname: `/components/NumericKeypad`; params?: Router.UnknownInputParams; } | { pathname: `/components/StepProgress`; params?: Router.UnknownInputParams; } | { pathname: `/components/TopicCard`; params?: Router.UnknownInputParams; } | { pathname: `/data/topics`; params?: Router.UnknownInputParams; } | { pathname: `/types/math`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/exercise/[id]` | `/exercise/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/challenges` | `/challenges`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ExerciseCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ExerciseStep`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MultipleChoiceOption`; params?: Router.UnknownOutputParams; } | { pathname: `/components/NumericKeypad`; params?: Router.UnknownOutputParams; } | { pathname: `/components/StepProgress`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TopicCard`; params?: Router.UnknownOutputParams; } | { pathname: `/data/topics`; params?: Router.UnknownOutputParams; } | { pathname: `/types/math`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(tabs)'}/exercise/[id]` | `/exercise/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/challenges${`?${string}` | `#${string}` | ''}` | `/challenges${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/practice${`?${string}` | `#${string}` | ''}` | `/practice${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/components/ExerciseCard${`?${string}` | `#${string}` | ''}` | `/components/ExerciseStep${`?${string}` | `#${string}` | ''}` | `/components/MultipleChoiceOption${`?${string}` | `#${string}` | ''}` | `/components/NumericKeypad${`?${string}` | `#${string}` | ''}` | `/components/StepProgress${`?${string}` | `#${string}` | ''}` | `/components/TopicCard${`?${string}` | `#${string}` | ''}` | `/data/topics${`?${string}` | `#${string}` | ''}` | `/types/math${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/challenges` | `/challenges`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExerciseCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExerciseStep`; params?: Router.UnknownInputParams; } | { pathname: `/components/MultipleChoiceOption`; params?: Router.UnknownInputParams; } | { pathname: `/components/NumericKeypad`; params?: Router.UnknownInputParams; } | { pathname: `/components/StepProgress`; params?: Router.UnknownInputParams; } | { pathname: `/components/TopicCard`; params?: Router.UnknownInputParams; } | { pathname: `/data/topics`; params?: Router.UnknownInputParams; } | { pathname: `/types/math`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(tabs)'}/exercise/${Router.SingleRoutePart<T>}` | `/exercise/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/exercise/[id]` | `/exercise/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
